### ISSUE TITLE
spin_(un,)lock for non-x86_64 is neither spinning or (exclusive) locking

### ISSUE THREAD

**Issue by grooverdan** [concurrencykit/ck#116]
ck/regressions/ck_spinlock/linux_spinlock.h
```*lock = (1|1);``` isn't a complete lock implementation.

Sure its only the regression test.

**Comment by sbahra** [comment]
linux_spinlock is not an implementation exported by Concurrency Kit. It is an internal x86-64 implementation, used as a reference point for benchmarking (it is the Linux kernel spinlock algorithm). The x86-64 implementation is correct.

If you're asking this to be ported to other platforms, patches are welcome, but this isn't a priority for me at the moment and it doesn't improve state of Concurrency Kit (since it's a reference for benchmarking on x86-64, other platforms still have benchmarks to the exported CK implementations).
