### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [concurrencykit/ck#30]
I would like to point out that identifiers like "[`_CK_FIFO_H`](https://github.com/concurrencykit/ck/blob/851098b5529c037bdc58eeafe2e5cfab62fd2dbb/include/ck_fifo.h#L28)" and "[`_CK_PR_H`](https://github.com/concurrencykit/ck/blob/14744714453530139b0f58e9bb94671d70c20871/include/ck_pr.h#L28)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by sbahra** [comment]
Thanks for the report. We know this, but as the link points out it is fairly common practice (especially in freestanding environments). It has also not been a problem in any target environments so far. Due to this, it has been fairly low priority for me.

I'll see if I can get to this later today (this is going to be a rather noisy release, anyways).

**Comment by sbahra** [comment]
Fixed, thanks again!

**Comment by elfring** [comment]
Thanks for [your improvement of the affected include guards](https://github.com/concurrencykit/ck/commit/554e2f0874baddf957388add4f7868fb18083ddc "Renaming of include guards").
