### ISSUE TITLE
feature parity across all supported platforms: undo @f6a2cb1

### ISSUE THREAD

**Issue by mhaberler** [concurrencykit/ck#58]
the issue with @f6a2cb1b39326e90e5e1cd2789741d60808340dd (ck_pr/x86_32: Drop 64-bit operations..) is:  it breaks feature parity across platforms, requiring ck users to fall back on emulating the missing operations with gcc/clang atomics or other means on that platform

I think 'feature parity on all supported platforms' would constitute a valuable goal for ck, as one could use it as a drop-in portability layer, and I would rate that goal higher than 'supporting only operations which perform better as builtins'. 

I explicitly do not mind certain operations being less-than-optimal performers, for instance by falling back on cc-provided builtins.

Of course it remains sensible to exclude those operations a given platform just cannot support, like arm6 and 64bit atomics.

**Comment by sbahra** [comment]
This requires a bit more work as the right combination of flags with PIC builds require us to manually save and restore register state. I'm due to hack on ck_hm during flights this week and will unlikely have time to get to this then. I can get to this last weekend of this month unless you or @cognet wanted to pick it up.

**Comment by sbahra** [comment]
It seems no one had time for this. Feel free to re-open if someone wants to address this.
